### ISSUE TITLE
ERROR: fast fp8 ops is not supported

### ISSUE THREAD

**Issue by ryukbk** [Haoming02/sd-webui-forge-classic#98]
Hi, when launching this on RTX 5090 with torch 2.7.1 + CUDA 12.8 and loading any checkpoint, I always get

> UNet dtype: torch.float8_e4m3fn
> 
> 
> ERROR: fast fp8 ops is not supported

Is this by design or an error that can be fixed?
[Store UNet Weights in fp8] and [Inference UNet in fast fp8 operations] are checked in the settings.
Using flash-attn now but this error is always shown regardless of which attention I use.

**Comment by Haoming02** [comment]
Should be fixed now~

*(the logic was left at detecting RTX 40s...)*

**Comment by ryukbk** [comment]
@Haoming02 Thanks, verified the fix. However, I installed the nightly of Pytorch 2.8.0 and the issue came back. Could you please take a look at it as well?

pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

> UNet dtype: torch.float16
> 
> 
> ERROR: fast fp8 ops is not supported

**Comment by Haoming02** [comment]
The only way "fast fp8 ops is not supported" gets printed, is when the `support_fp8()` function returns `False`.

And the function only checks:

1. `fp8_storage` is enabled
2. Nvidia GPU
3. PyTorch > `2.4.0`
4. Cuda Compute > `8.9`

```py
def support_fp8():
    if not prefer_fp8():
        return False
    if not is_nvidia():
        return False

    if int(torch_version[0]) < 2 or int(torch_version[2]) < 4:
        return False

    device = get_torch_device()
    props = torch.cuda.get_device_properties(device)

    if props.major >= 9:
        return True
    elif props.major == 8 and props.minor >= 9:
        return True
    else:
        return False
```

So in theory, this should work...

<hr>

Try modifying the [model_management.py](https://github.com/Haoming02/sd-webui-forge-classic/blob/classic/ldm_patched/modules/model_management.py#L733), and force it to return `True` I guess...

```py
def support_fp8():
    return True
```

**Comment by Haoming02** [comment]
> UNet dtype: torch.float16

Wait, is `fp8_storage` enabled?

**Comment by ryukbk** [comment]
@Haoming02 Oh I unchecked this one earlier
>Store UNet Weights in fp8

Does it affect that message? If so, this message
>ERROR: fast fp8 ops is not supported

might not be immediately clear to be related to that option

**Comment by Haoming02** [comment]
Yes, the `fast fp8 operation` **requires** `UNet in fp8`.

I will update the description to clarify that.
